//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeganFoodsBusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipeingredients
    {
        public int FK_RecipeID { get; set; }
        public int FK_IngredientID { get; set; }
        public Nullable<int> Measurement { get; set; }
        public string MeasurementType { get; set; }
    
        public virtual ingredients ingredients { get; set; }
        public virtual recipes recipes { get; set; }
    }
}
